### ISSUE TITLE
Problem when installing yolox

### ISSUE THREAD

**Issue by luciaschmid** [mcmingchang/yolox_keypoint_segment#14]
I see this AssertionError when installing yolox when calling the pip install -v -e . step.
I previously used python3.9, where I had the same issue. I hoped that downgrading to Python3.8 would solve it, but it didn't. I downgraded from setuptools69.1.1 to setuptools-62.6.0.
What else could I try to make it work?
`
(.venv) (base) ubuntu@ip-10-150-129-58:~/yolox_keypoint_segment$ python -m pip install -v -e .
Using pip 24.0 from /home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/pip (python 3.8)
Obtaining file:///home/ubuntu/yolox_keypoint_segment
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info
  writing /tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info/SOURCES.txt'
  package init file 'exps/default/__init__.py' not found (or not a regular file)
  reading manifest file '/tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-rvow2iur/yolox.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (1.24.4)
Requirement already satisfied: torch>=1.7 in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (2.2.1)
Requirement already satisfied: opencv_python in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (4.9.0.80)
Requirement already satisfied: loguru in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (0.7.2)
Requirement already satisfied: scikit-image in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (0.21.0)
Requirement already satisfied: tqdm in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (4.66.2)
Requirement already satisfied: torchvision in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (0.17.1)
Requirement already satisfied: Pillow in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (10.2.0)
Requirement already satisfied: thop in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (0.1.1.post2209072238)
Requirement already satisfied: ninja in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (1.11.1.1)
Requirement already satisfied: tabulate in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (0.9.0)
Requirement already satisfied: tensorboard in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (2.14.0)
Requirement already satisfied: pycocotools>=2.0.2 in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (2.0.7)
Requirement already satisfied: onnx==1.8.1 in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (1.8.1)
Requirement already satisfied: onnxruntime==1.8.0 in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (1.8.0)
Requirement already satisfied: onnx-simplifier==0.3.5 in ./.venv/lib/python3.8/site-packages (from yolox==0.3.0) (0.3.5)
Requirement already satisfied: protobuf in ./.venv/lib/python3.8/site-packages (from onnx==1.8.1->yolox==0.3.0) (4.25.3)
Requirement already satisfied: six in ./.venv/lib/python3.8/site-packages (from onnx==1.8.1->yolox==0.3.0) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./.venv/lib/python3.8/site-packages (from onnx==1.8.1->yolox==0.3.0) (4.10.0)
Requirement already satisfied: onnxoptimizer>=0.2.5 in ./.venv/lib/python3.8/site-packages (from onnx-simplifier==0.3.5->yolox==0.3.0) (0.3.13)
Requirement already satisfied: flatbuffers in ./.venv/lib/python3.8/site-packages (from onnxruntime==1.8.0->yolox==0.3.0) (23.5.26)
Requirement already satisfied: matplotlib>=2.1.0 in ./.venv/lib/python3.8/site-packages (from pycocotools>=2.0.2->yolox==0.3.0) (3.7.5)
Requirement already satisfied: filelock in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (3.13.1)
Requirement already satisfied: sympy in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (1.12)
Requirement already satisfied: networkx in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (3.1)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (3.1.3)
Requirement already satisfied: fsspec in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (12.1.105)
Requirement already satisfied: triton==2.2.0 in ./.venv/lib/python3.8/site-packages (from torch>=1.7->yolox==0.3.0) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in ./.venv/lib/python3.8/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.7->yolox==0.3.0) (12.3.101)
Requirement already satisfied: scipy>=1.8 in ./.venv/lib/python3.8/site-packages (from scikit-image->yolox==0.3.0) (1.10.1)
Requirement already satisfied: imageio>=2.27 in ./.venv/lib/python3.8/site-packages (from scikit-image->yolox==0.3.0) (2.34.0)
Requirement already satisfied: tifffile>=2022.8.12 in ./.venv/lib/python3.8/site-packages (from scikit-image->yolox==0.3.0) (2023.7.10)
Requirement already satisfied: PyWavelets>=1.1.1 in ./.venv/lib/python3.8/site-packages (from scikit-image->yolox==0.3.0) (1.4.1)
Requirement already satisfied: packaging>=21 in ./.venv/lib/python3.8/site-packages (from scikit-image->yolox==0.3.0) (23.2)
Requirement already satisfied: lazy_loader>=0.2 in ./.venv/lib/python3.8/site-packages (from scikit-image->yolox==0.3.0) (0.3)
Requirement already satisfied: absl-py>=0.4 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (2.1.0)
Requirement already satisfied: grpcio>=1.48.2 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (1.62.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (2.28.1)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (3.5.2)
Requirement already satisfied: requests<3,>=2.21.0 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (2.31.0)
Requirement already satisfied: setuptools>=41.0.0 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (62.6.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (3.0.1)
Requirement already satisfied: wheel>=0.26 in ./.venv/lib/python3.8/site-packages (from tensorboard->yolox==0.3.0) (0.42.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.venv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard->yolox==0.3.0) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.venv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard->yolox==0.3.0) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in ./.venv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard->yolox==0.3.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.venv/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard->yolox==0.3.0) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in ./.venv/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard->yolox==0.3.0) (7.0.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->yolox==0.3.0) (1.1.1)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->yolox==0.3.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->yolox==0.3.0) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.venv/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->yolox==0.3.0) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->yolox==0.3.0) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->yolox==0.3.0) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in ./.venv/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->yolox==0.3.0) (6.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->yolox==0.3.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->yolox==0.3.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->yolox==0.3.0) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->yolox==0.3.0) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./.venv/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard->yolox==0.3.0) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in ./.venv/lib/python3.8/site-packages (from sympy->torch>=1.7->yolox==0.3.0) (1.3.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.8/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->yolox==0.3.0) (3.17.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in ./.venv/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->yolox==0.3.0) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in ./.venv/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard->yolox==0.3.0) (3.2.2)
Installing collected packages: yolox
  Running setup.py develop for yolox
    Running command python setup.py develop
    running develop
    running egg_info
    writing yolox.egg-info/PKG-INFO
    writing dependency_links to yolox.egg-info/dependency_links.txt
    writing requirements to yolox.egg-info/requires.txt
    writing top-level names to yolox.egg-info/top_level.txt
    /home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    package init file 'exps/default/__init__.py' not found (or not a regular file)
    reading manifest file 'yolox.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'yolox.egg-info/SOURCES.txt'
    running build_ext
    building 'yolox.layers.fast_cocoeval' extension
    Emitting ninja build file /home/ubuntu/yolox_keypoint_segment/build/temp.linux-x86_64-cpython-38/build.ninja...
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/ubuntu/yolox_keypoint_segment/setup.py", line 64, in <module>
        setuptools.setup(
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
        return run_commands(dist)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
        dist.run_commands()
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
        self.run_command(cmd)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
        super().run_command(command)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
        super().run_command(command)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 871, in build_extensions
        build_ext.build_extensions(self)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 459, in build_extensions
        self._build_extensions_serial()
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 485, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
        super(build_ext, self).build_extension(ext)
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 540, in build_extension
        objects = self.compiler.compile(
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 684, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1760, in _write_ninja_file_and_compile_objects
        _write_ninja_file(
      File "/home/ubuntu/yolox_keypoint_segment/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2292, in _write_ninja_file
        assert len(sources) > 0
    AssertionError
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/ubuntu/yolox_keypoint_segment/.venv/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/ubuntu/yolox_keypoint_segment/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/ubuntu/yolox_keypoint_segment/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by ksv87** [comment]
You need copy directory yolox/layers/cocoeval from https://github.com/Megvii-BaseDetection/YOLOX/tree/main/yolox/layers
